name: Daily SharePoint Cheque Reminder

on:
  schedule:
    # Runs daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: "0 9 * * *"

  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      test_run:
        description: "Test run - sends reminder regardless of date"
        required: false
        default: "false"

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # Cache pip dependencies for faster builds

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the reminder script
      - name: Run SharePoint reminder check
        env:
          # Environment variables from GitHub secrets
          SHAREPOINT_SHARED_URL: ${{ secrets.SHAREPOINT_SHARED_URL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          TEST_RUN: ${{ github.event.inputs.test_run }}
        run: python sharepoint_reminder.py

      # Step 5: Upload logs as artifacts (for debugging)
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always() # Upload even if previous steps failed
        with:
          name: reminder-logs-${{ github.run_number }}
          path: |
            *.log
            logs/
          retention-days: 30

      # Step 6: Send notification on failure (optional)
      - name: Send failure notification
        if: failure()
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python -c "
          import smtplib
          from email.mime.text import MIMEText
          from datetime import datetime
          import os

          msg = MIMEText('The SharePoint cheque reminder script failed to run successfully. Please check the GitHub Actions logs for details.')
          msg['Subject'] = '⚠️ SharePoint Reminder Script Failed - ' + datetime.now().strftime('%Y-%m-%d')
          msg['From'] = os.getenv('EMAIL_USERNAME')
          msg['To'] = os.getenv('RECIPIENT_EMAIL')

          try:
              server = smtplib.SMTP(os.getenv('SMTP_SERVER'), int(os.getenv('SMTP_PORT')))
              server.starttls()
              server.login(os.getenv('EMAIL_USERNAME'), os.getenv('EMAIL_PASSWORD'))
              server.send_message(msg)
              server.quit()
              print('Failure notification sent')
          except Exception as e:
              print(f'Failed to send notification: {e}')
          "
